### ISSUE TITLE
Provide data for project creation

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal#10]
I'd like to start running the github project creation code on Monday. Could I get a function (on whatever `XXX` makes the most sense to you:

`XXX.getGroupDescriptions() : GroupRepoDescription[]`

```
interface GroupRepoDescription {
    team: number;
    members: string[]; // github usernames
    url?: string;
}
```

Also, having a method where I can call `XXX.setGithubURL(teamId, url)` when the teams are created would also be fantastic.

**Comment by rtholmes** [comment]
@mksarge, we're up to 59 registered teams now; everything seems to be working great!

**Comment by rtholmes** [comment]
@mksarge it would be nice to be able to run this tomorrow, if you have a minute to get to this. Hopefully it's only a short method. I went poking around but was worried I would do more harm than good.

**Comment by mksarge** [comment]
I'm getting on it now!

**Comment by rtholmes** [comment]
Awesome, thanks so much!
