### ISSUE TITLE
Browser-compatibility issues

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal#11]
Reported from a student:

Just FYI, the link to the ClassPortal is broken in Safari (although it works in chrome).

Found this error in the console while looking at the source:

SyntaxError: Cannot declare a parameter named 'error' as it shadows the name of a strict mode function.
(anonymous function)bundle.js:29160

**Comment by mksarge** [comment]
Renaming this issue to cover all browser-related display issues.

**These browsers seem to be working so far:**
Linux desktop - Firefox, Chrome
OS X - Firefox, Chrome
Windows - Firefox, Chrome, Microsoft Edge!
Android - Firefox, Default OS browser

**These browsers do not display the site correctly:**
iOS - Safari, Firefox, Chrome, Dolphin (all display blank screen)
OS X - Safari (error posted above)
Android - Chrome (Log in button redirect forces app switch to Firefox on my device)

I will edit these lists as new bugs are discovered or new fixes are made.

**Comment by rtholmes** [comment]
OS X: Chrome & Firefox work perfectly. Safari gives the error shown in the original report above.
