### ISSUE TITLE
Grading

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal#12]
@mksarge just checking on progress?

**Comment by mksarge** [comment]
Going to push tonight! Sorry for the delays

**Comment by rtholmes** [comment]
I'm wondering if there is a simpler format for `grades.json`:

```
[
  {did: 'd1', sid: 'studnum', grade: 72, comments: 'some optional text' }
  ...
]
```

This would make it so you wouldn't have to put anything in in advance (which would make it easier to change the list of deliverables or the student list); if an entry isn't there it would just be `-` in the UI and if you added a team grade you could just put N entries in the file (one per team-member). Would this make things simpler? Right now it looks like the data we have in `grades.json` is going to be problematic to upgrade to the new format.

**Comment by rtholmes** [comment]
Two questions:
- Can we remove the confirm and success dialogs for grade addition? It's just too much clicking that is going to be yes 99.999% of the time.
- Are the grades released as they are entered or can we just set a boolean in the deliverables.json  (e.g.., `gradesReleased: true/false`) so the TAs can add grades without the students constantly refreshing in the background.

**Comment by mksarge** [comment]
Okay, I just removed those dialogs. And yep, I'll use a gradesReleased property in deliverables.json to determine whether the grade can be viewed on the Student portal.

**Comment by rtholmes** [comment]
- Should I add `gradesReleased: boolean` to all of my entries in `deliverables.json` now?
- Any chance the edit grades dialog could show the existing grade / feedback for a student if it has already been set (e.g., if I choose D1 for a student who already has a D1 grade?)

**Comment by mksarge** [comment]
- Yes!
- Actually, I already implemented a warning dialog just like that - it shows up **after** you press submit. Give it a try and let me know if it's adequate, or if you want the dialog to show up as soon as the assignment is selected.

**Comment by rtholmes** [comment]
gradesReleased added; all my entries look approximately like this now:

```
    {
        "id":"final",
        "name":"Final",
        "description":"",
        "url":"https://github.com/ubccpsc/310/blob/2016sept/README.md",
        "open": "Dec 9",
        "due": "Dec 9",
        "gradeRelease": "Dec 20",
        "gradesReleased": false,
        "isTeam": false,
        "uploadKind": ""
    }
```

The warning dialog is fine, I just mean when you click 'submit' on an existing student that has a grade for a deliverable and choose that deliverable from the dropdown the text/grade fields should show the already entered grade (like d1 or labs for the fake student in the class right now).

**Comment by mksarge** [comment]
Sure, I'll add that now.

Just another note, since it's not totally intuitive - if you click any grade on the Students View, it opens up another modal that shows all of that student's grades + comments. Not sure if that needs to be made more obvious?

**Comment by rtholmes** [comment]
No, I found that one, works totally fine.
